# Generated by Django 5.2.4 on 2025-09-06 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_sitesettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="comment_ban_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
