# Generated by Django 5.2.4 on 2025-09-06 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_profile_comment_ban_until"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="ban_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="comment",
            name="toxicity_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="comment",
            name="toxicity_label",
            field=models.CharField(
                blank=True, default="normal", max_length=50, null=True
            ),
        ),
    ]
