# Generated by Django 5.2.4 on 2025-09-06 07:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0011_comment_ban_until_comment_toxicity_score_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="downvotes",
            field=models.ManyToManyField(
                blank=True,
                related_name="comment_downvotes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="upvotes",
            field=models.ManyToManyField(
                blank=True, related_name="comment_upvotes", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
