# Generated by Django 5.2.4 on 2025-09-07 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0012_comment_downvotes_comment_upvotes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["created_at"]},
        ),
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="comment",
            name="ban_until",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="toxicity_score",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="comment",
            name="toxicity_label",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="genre",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
