# Generated by Django 5.2.4 on 2025-09-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0013_alter_comment_options_alter_post_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="view_count",
            field=models.PositiveIntegerField(
                default=0, help_text="This field is automatically updated."
            ),
        ),
    ]
