# Generated by Django 5.2.4 on 2025-09-11 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0014_post_view_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_featured",
            field=models.BooleanField(
                default=False,
                help_text="Set to True to make this the single featured post on the homepage.",
            ),
        ),
    ]
