# Generated by Django 5.2.4 on 2025-09-13 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0015_post_is_featured"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="github_username",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="profile",
            name="twitter_handle",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name="profile",
            name="website_url",
            field=models.URLField(blank=True),
        ),
    ]
