# Generated by Django 5.2.4 on 2025-09-14 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0016_profile_github_username_profile_twitter_handle_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserInquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("read", "Read"),
                            ("resolved", "Resolved"),
                        ],
                        default="new",
                        max_length=10,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-submitted_at"],
            },
        ),
    ]
