# Generated by Django 5.2.4 on 2025-09-15 14:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0018_comment_reported_by_alter_comment_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="reported_by",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users who have reported this comment.",
                related_name="reported_comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
