# Generated by Django 5.2.4 on 2025-09-15 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0019_alter_comment_reported_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="status",
            field=models.CharField(
                choices=[
                    ("approved", "Approved"),
                    ("pending_review", "Pending Review"),
                    ("rejected", "Rejected"),
                ],
                default="approved",
                max_length=20,
            ),
        ),
    ]
