# Generated by Django 5.2.4 on 2025-10-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0021_alter_comment_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("new_comment", "New Comment"),
                    ("new_reply", "New Reply"),
                    ("toxic_comment", "Toxic Comment"),
                    ("comment_approved", "Comment Approved"),
                ],
                default="new_comment",
                max_length=20,
            ),
        ),
    ]
