# Generated by Django 5.2.4 on 2025-10-28 05:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0022_alter_notification_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="reported_by",
            field=models.ManyToManyField(
                blank=True,
                related_name="reported_comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="is_featured",
            field=models.BooleanField(
                default=False, help_text="Only one post can be featured at a time."
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="view_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Automatically updated."
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                default="blog/images/default.jpg", upload_to="profile_pics"
            ),
        ),
    ]
