# Generated by Django 5.2.4 on 2025-10-28 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0023_alter_comment_reported_by_alter_post_is_featured_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                default="profile_pics/default.jpg", upload_to="profile_pics"
            ),
        ),
    ]
